name: deploy to lambda
permissions:
  id-token: write
  contents: read
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: package
        run: |
          zip lambda.zip lambda_function.py || true
      - name: cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::651845762820:role/github-OIDC-Role-JdfwPtWdASUt
      - name: deploy
        run: |
          aws lambda update-function-code --function-name enquiry --zip-file fileb://lambda.zip
